# Generated by Django 2.0.3 on 2018-04-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='suppress_from_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pie',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
