# Generated by Django 2.0.3 on 2018-04-09 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pie_convention'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='convention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Convention'),
        ),
    ]
