# Generated by Django 2.0.3 on 2018-09-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_game_convention'),
    ]

    operations = [
        migrations.AddField(
            model_name='pie',
            name='person_name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
